name: youthbit
description: youthbit hackathon project
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  surf_lint_rules: ^1.5.0
  riverpod_generator: ^1.1.1
  riverpod: ^2.1.3
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  easy_localization: ^3.0.1
  icons_launcher: ^2.0.6
  logger: ^1.1.0
  #  ar_flutter_plugin: ^0.7.3
  adaptive_dialog: ^1.8.2
  flutter_native_splash: ^2.2.16
  scroll_pos: ^0.3.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  google_fonts: ^4.0.2
  freezed_annotation: ^2.2.0
  json_annotation: any
  flutter_emoji: ^2.4.0
  card_swiper: ^2.0.4
  dio: ^4.0.6
  get_it: ^7.2.0
  flutter_svg: 1.1.6
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  go_router: ^6.0.3
  flutter_swiper: ^1.1.6
  flutter_secure_storage: ^7.0.1
  shrink_sidemenu: ^2.0.0+2-null-safety
  custom_navigation_bar: ^0.8.2
  xml: ^6.2.2
  shake: ^2.2.0
  debug_overlay: ^0.2.6
  multiple_result: ^4.0.0
  flame: ^1.6.0
  rxdart: ^0.27.5
  quiver: ^3.1.0
  flutter_gif: ^0.0.4
  hive: ^2.2.3
  equatable: ^2.0.5
  flutter_point_tab_bar: ^0.2.0
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  google_maps_cluster_manager: ^3.0.0+1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  custom_sliding_segmented_control: ^1.7.4
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  expandable_text: ^2.3.0
  tuple: ^2.0.1
  calendar_date_picker2: ^0.3.9
  modal_bottom_sheet: ^2.1.2
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.4
  webview_flutter: ^4.0.2
  webview_flutter_wkwebview: ^3.1.0
  webview_flutter_android: ^3.3.0
  story_view: ^0.14.0
  timelines: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: any
  isar_generator: ^3.0.5
  json_serializable: ^6.5.4
flutter:
  uses-material-design: true
  shaders:
    - assets/radar.glsl
  assets:
    - assets/translations/
    - assets/svg/
    - assets/svg/light/
    - assets/svg/dark/
    - assets/images/
    - assets/achievements/
    - assets/avatars/accessories/
    - assets/avatars/body/
    - assets/avatars/face/
    - assets/avatars/facial-hair/
    - assets/avatars/head/
    - assets/avatars/background/
    - assets/map_styles/
    - assets/gifs/
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  color_dark: "#FFFFFF"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
  fullscreen: true